
vars:
  grafana_admin_user: "admin"
  grafana_admin_password: "admin"
  grafana_version: "10.2.0"
  grafana_port: 3000
  prometheus_version: "2.47.0"
  prometheus_port: 9090
  node_exporter_version: "1.6.1"
  node_exporter_port: 9100
  domain_name: "3.105.85.131"






# ---
# # Configuration Grafana
# grafana_version: "10.2.0"
# grafana_port: 3000
# grafana_admin_user: admin
# grafana_admin_password: "admin123!"  # Ã€ changer en prod

# # Configuration Prometheus
# prometheus_version: "2.47.0"
# prometheus_port: 9090

# # Configuration Node Exporter
# node_exporter_version: "1.6.1"
# node_exporter_port: 9100

# # Domaines
# domain_name: "3.24.179.195"  # Votre IP EC2


