---
- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes

- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: Ouvrir le port Node Exporter
  firewalld:
    port: "{{ node_exporter_port }}/tcp"
    permanent: yes
    state: enabled
  notify: reload-firewalld

# roles/prometheus/handlers/main.yml

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes


# roles/prometheus/handlers/main.yml

- name: reload-firewalld
  command: firewall-cmd --reload


- name: Ouvrir le port Prometheus
  firewalld:
    port: "{{ prometheus_port }}/tcp"
    permanent: yes
    state: enabled
  notify: reload-firewalld


- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes


