---
- name: Créer l'utilisateur node_exporter
  user:
    name: node_exporter
    system: yes
    shell: /bin/false

- name: Télécharger Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extraire Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"  # Vérifie si le fichier existe

- name: Vérifier que le fichier node_exporter existe
  stat:
    path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
  register: node_exporter_stat

- name: Afficher les informations sur le fichier node_exporter
  debug:
    msg: "Le fichier node_exporter existe : {{ node_exporter_stat.stat.exists }}"

- name: Installer Node Exporter
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: yes  # Ajouter cette option pour indiquer que le fichier est sur la machine distante
  when: node_exporter_stat.stat.exists  # Installer seulement si le fichier existe
  notify: restart node_exporter


- name: Créer le service systemd
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - daemon-reload
    - restart node_exporter

- name: Démarrer et activer Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Ouvrir le port Node Exporter
  firewalld:
    port: "{{ node_exporter_port }}/tcp"
    permanent: yes
    state: enabled
  notify: reload-firewalld
